

language: go
go_import_path: github.com/qmuntal/gopc

go:
  - 1.10.x
  - 1.11.x

env:
  - GO111MODULE=on

notifications:
  - email: false

before_script:
  - make setup  

script:
  - go test  ./... -coverprofile=coverage.out -race -timeout=5s
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
